services:
  mysqldump-tailscale:
    container_name: docker-mysqldump-tailscale
    build:
      context: .
      dockerfile: mysql-8.Dockerfile
    restart: no
    volumes:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    env_file:
      - ./.env.dev
      